language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: true
    install: chmod +x $TRAVIS_BUILD_DIR/.travis_install_dependencies.sh && $TRAVIS_BUILD_DIR/.travis_install_dependencies.sh
    script: chmod +x $TRAVIS_BUILD_DIR/.travis_compile.sh && $TRAVIS_BUILD_DIR/.travis_compile.sh
    env: BUILD_TYPE=Release SFML_VER=2.5.1
  - os: linux
    sudo: true
    dist: trusty
    install: chmod +x $TRAVIS_BUILD_DIR/.travis_install_dependencies.sh && $TRAVIS_BUILD_DIR/.travis_install_dependencies.sh
    script: chmod +x $TRAVIS_BUILD_DIR/.travis_compile.sh && $TRAVIS_BUILD_DIR/.travis_compile.sh
    env: BUILD_TYPE=Debug SFML_VER=2.5.1
addons:
  artifacts:
    paths:
    - ~/build/Tardo/MVRunner/build-Release/MVRunner
    - ~/build/Tardo/MVRunner/build-Debug/MVRunner_d
    - ~/build/Tardo/MVRunner/build-Release/*.tar.gz
